# kafka配置 192.168.56.125
spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 25MB # 限制文件上传大小为10M
      max-request-size: 100MB
storage-config:
  endpoint: http://101.126.129.1:9000
  bucketName: storage
  accessKey: xEZi8r2rSrzyujpfTKpG
  secretKey: h2YL5HcbKCuGKZFRzvaFcUQ3VYWMwe1C5FQGCpFF
  region: cn-south-1
